import React from 'react'
import Head from 'next/head'
import NavBar from '@/components/layout/NavBar'

interface LayoutProps {
  children: React.ReactNode
}

function Layout({ children }: LayoutProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Validation demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <NavBar />
      {children}
    </>
  )
}

export default Layout
